### ISSUE TITLE
Add name of MS thesis

### ISSUE THREAD

**Issue by nav-mike** [IPMITMO/LOD-Scientific-Search#1]
Поиск научного и образовательного контента на основе открытых данных

**Comment by nav-mike** [comment]
@iradche, need review, please 🔥

**Comment by iradche** [comment]
"Разработка поисковой системы научного и образовательного контента на основе связанных открытых данных".

**Comment by nav-mike** [comment]
I like

**Comment by nav-mike** [comment]
@GitGeras you should use this name for docs :zap:

**Comment by nav-mike** [comment]
@GitGeras Open Linked Data

**Comment by iradche** [comment]
@GitGeras, @nav-mike 
1. See revised version at https://github.com/IPMITMO/LOD-Scientific-Search/tree/master/docs.  
2.  Add name 'Разработка информационно-поисковой системы научного и образовательного контента на основе открытых данных' to all your docs.

**Comment by ogerasin** [comment]
1. New version - https://github.com/IPMITMO/LOD-Scientific-Search/blob/master/docs/Individual_Plan_Gerasin.doc
2. In individual plan we write "Тематика", not "Тема"

**Comment by iradche** [comment]
I didn't see my changes that I've made in my revised version. So the newest version is not suitable.

**Comment by ogerasin** [comment]
This is the brand new version that's why you don't see your changes

**Comment by iradche** [comment]
Please merge it correctly.
