### ISSUE TITLE
Read articles about lod.ifmo

### ISSUE THREAD

**Issue by nav-mike** [IPMITMO/LOD-Scientific-Search#10]
1. http://ntv.ifmo.ru/ru/article/14097/issledovanie_aktualnyh_sposobov_publikacii_otkrytyh_nauchnyh_dannyh_v_seti.htm

2. https://www.academia.edu/28121326/%D0%A1%D0%B2%D1%8F%D0%B7%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5_%D0%BE%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8B%D0%B5_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5_%D0%B2_%D1%83%D0%BD%D0%B8%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%82%D0%B5%D1%82%D0%B5

**Comment by iradche** [comment]
@nav-mike  Do we have a repo with all links about LOD-ITMO?

**Comment by nav-mike** [comment]
https://github.com/AKSW/itmolod - public repo

@iradche I think we need transfer (or fork) repo to https://github.com/LODIFMO organization or to https://github.com/IPMITMO

**Comment by nav-mike** [comment]
@GitGeras [github.com/LODIFMO/itmolod](https://github.com/LODIFMO/itmolod) - public repo of [lod.ifmo.ru](http://lod.ifmo.ru/)
