### ISSUE TITLE
Understand deployment tools (not important, background task) 

### ISSUE THREAD

**Issue by nav-mike** [IPMITMO/LOD-Scientific-Search#11]
Understand vagrant, docker, ansible (deploy app to server process)

**Comment by iradche** [comment]
@GitGeras @nav-mike   It's interesting to see your container after all.

**Comment by nav-mike** [comment]
@iradche @GitGeras I think we need use docker: https://docs.docker.com/swarm/swarm_at_scale/deploy-app and https://habrahabr.ru/post/238069/ (but rails)

I usually use capistrano to deploy applications, but it for ruby apps. Docker will a good solution.

**Comment by iradche** [comment]
What about C9?

**Comment by nav-mike** [comment]
@iradche c9 is not deployment tool. It's cloud IDE. But we can use C9 if you want.
@GitGeras if you will have a free time, try to use [c9.io](https://c9.io), please.
