### ISSUE TITLE
Create a plan of works

### ISSUE THREAD

**Issue by iradche** [IPMITMO/LOD-Scientific-Search#2]

**Comment by nav-mike** [comment]
1. Find analogues and search algorithms, technologies etc.
2. Development models
3. Develop prototype.
4. Deploy prototype and testing, experiment.

**Comment by GitGeras** [comment]
I think it's Rubby, not Pubby, isn't it?

**Comment by iradche** [comment]
Where could I find the docs?

**Comment by nav-mike** [comment]
@GitGeras :exclamation: add docs to repo, pls

**Comment by ogerasin** [comment]
@iradche @nav-mike
https://github.com/IPMITMO/LOD-Scientific-Search/blob/master/Individual_Plan.doc

**Comment by iradche** [comment]
https://github.com/IPMITMO/LOD-Scientific-Search/pull/12
