### ISSUE TITLE
Meeting 2

### ISSUE THREAD

**Issue by nav-mike** [IPMITMO/LOD-Scientific-Search#7]
- [x] 📦  Django app (development, test, staging, deploy, capistrano, ansible)

- [x] 🌎  Ontology (Разработка онтологий 101: руководство по созданию Вашей первой онтологии[1]
Наталья Ф. Ной (Natalya F. Noy) и Дэбора Л. МакГиннесс (Deborah L. McGuinness)
Стэнфордский Университет, Стэнфорд, Калифорния, classes, fields, properties, protege)

- [x] 🚀  SPARQL (SPARQL-endpoint, insert, delete, select, ask)

- [x] ☕️  Jena, RDF.rb, etc.

1. http://ntv.ifmo.ru/ru/article/14097/issledovanie_aktualnyh_sposobov_publikacii_otkrytyh_nauchnyh_dannyh_v_seti.htm

1. https://www.academia.edu/28121326/Связанные_открытые_данные_в_университете

**Comment by iradche** [comment]
@nav-mike @GitGeras Please use one place for all links.
And when are you going to meetup next time?

**Comment by ogerasin** [comment]
I've written in the table
15 November, about 15-00

**Comment by nav-mike** [comment]
@iradche I write each meetup like a [milestone](https://github.com/IPMITMO/LOD-Scientific-Search/milestones) due date.
